server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: web-consumer
  redis:
    host: localhost
    port: 6380

  profiles: default
  freemarker:
    template-loader-path: classpath:/templates
    cache: true
    check-template-location: true
    content-type: text/html; charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  main:
    allow-bean-definition-overriding: true #允许相同key情况下beanDefinition实例的覆盖
  thymeleaf:
    enabled: true
    mode: LEGACYHTML5
    cache: false


feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000
elasticsearch:
  thirdPort: 9302
  secondPort: 9301
  clusterName: my-application
  ip: 127.0.0.1
  firstPort: 9300
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000



