server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    lease-renewal-interval-in-seconds: 1     #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，
    #server端没有收到client的心跳，则将摘除该instance
    lease-expiration-duration-in-seconds: 2 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，
    #在这个时间内若没收到下一次心跳，则将移除该instance
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*Mapper.xml

spring:
  #redis连接池信息
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 20000
    database: 0
    #配置哨兵集群
    sentinel:
      master: mymaster
      nodes: 192.168.68.141:26379,192.168.68.141:26380,192.168.68.141:26381
    cluster:
      #配置redis集群
      nodes: 192.168.68.141:6379,192.168.68.141:6380,192.168.68.141:6381
  application:
    name: web-provider
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/cinema?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application


